<?php
/**
 * Magedelight
 * Copyright (C) 2015 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category MD
 * @package MD_Partialpayment
 * @copyright Copyright (c) 2015 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
$helper		   = Mage::helper('md_partialpayment');
$payment	   = $this->getPayment();
$store		   = Mage::app()->getStore($payment->getStoreId());
$order		   = $payment->getOrder();
$orderItem	   = $payment->getOrderItem();
$summaryCollection = $payment->getPaymentSummaryCollection();
$ids		   = $summaryCollection->getAllIds();
$summaryStatusMap  = array(
    MD_Partialpayment_Model_Summary::PAYMENT_FAIL => array(
	"label"    => $helper->__('Failed'), 
	"class"	   => "grid-severity-critical"
    ),
    MD_Partialpayment_Model_Summary::PAYMENT_PENDING => array(
	"label"	   => $helper->__('Pending'), 
	"class"	   => "grid-severity-minor"
    ),
    MD_Partialpayment_Model_Summary::PAYMENT_SUCCESS => array(
	"label"	   => $helper->__('Paid'), 
	"class"	   => "grid-severity-notice"
    ),
    MD_Partialpayment_Model_Summary::PAYMENT_HOLD => array(
	"label"	   => $helper->__('Hold'), 
	"class"	   => "grid-severity-critical"
    ),
    MD_Partialpayment_Model_Summary::PAYMENT_DECLINED => array(
	"label"	   => $helper->__('Declined'), 
	"class"	   => "grid-severity-critical"
    ),
    MD_Partialpayment_Model_Summary::PAYMENT_PROCESS => array(
	"label"	   => $helper->__('Processing'), 
	"class"    => "grid-severity-critical"
    ),
);

$name = array(
    $store->getWebsite()->getName(),
    $store->getGroup()->getName(),
    $store->getName()
);
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4>
	    <a href="<?php echo $this->getViewUrl($payment->getId()) ?>">
	    <?php 
	    $paymentInfoTitle  = $helper->__('Payment Installment Summary for Order # ');
	    $paymentInfoTitle .= $order->getIncrementId();
	    
	    echo $paymentInfoTitle; 
	    ?>
	    </a>
	</h4>
    </div>
<form method="post" id="payment-summary-form" name="payment.summary.form" action="<?php echo Mage::helper('adminhtml')->getUrl('md_partialpayment/adminhtml_summary/pay', array("payment_id" => $payment->getId())) ?>">
    <input type="hidden" id="total_due" value="<?php echo $order->getdata('total_due'); ?>" />
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />

    <div class="grid np" id="paymentsummarytable">
        <div class="hor-scroll">
            <table cellspacing="0" class="data order-tables" style="width:100%;" id="my-summary-table">
                <colgroup>
                    <col width="1"/>
                    <col width="1"/>
                    <col />
                    <col />
                    <col />
                    <col />
                    <col width="1"/>
                    <col/>
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th class="a-center"><?php echo $helper->__('Amount') ?></th>
                        <th class="a-center"><?php echo $helper->__('Due Date') ?></th>
                        <th class="a-center"><?php echo $helper->__('Paid Date') ?></th>
                        <th class="a-center"><?php echo $helper->__('Status') ?></th>
                        <th class="a-center"><?php echo $helper->__('Payment Method') ?></th>
                        <th class="a-center"><?php echo $helper->__('Details') ?></th>
                    </tr>
                </thead>
                <tbody>
		    <?php $unpaid = true; ?>
		    <?php foreach ($summaryCollection as $summary): ?>

			<?php
			$transactionDetails = $summary->getTransactionDetails();
			$transactionDetails = (!empty($summary->getTransactionDetails())) ? implode('<br />', unserialize($summary->getTransactionDetails())) : '-'; ?>
    		    <tr>
    			<?php $disabled = (in_array($summary->getStatus(), array(MD_Partialpayment_Model_Summary::PAYMENT_SUCCESS, MD_Partialpayment_Model_Summary::PAYMENT_PROCESS))) ? true : false; ?>
    			<td class="a-left" style="width: 200px">
    			    <div id="orgsummaryparent_<?php echo $summary->getData('summary_id'); ?>">
				    <?php echo Mage::app()->getLocale()->currency($order->getOrderCurrencyCode())->getSymbol(); ?>
    				<span id="changeamount_<?php echo $summary->getData('summary_id'); ?>">
					<?php echo number_format((float) $summary->getAmount(), 2, '.', '') ?>
    				</span>
    			    </div>
    			    <div id="changesummaryparent_<?php echo $summary->getData('summary_id'); ?>" style="display: none;">
				    <?php echo Mage::app()->getLocale()->currency($order->getOrderCurrencyCode())->getSymbol(); ?>
    				<input type="text" name="summarychange_<?php echo $summary->getData('summary_id'); ?>" value="<?php echo number_format((float) $summary->getAmount(), 2, '.', '') ?>" id="summarychange_<?php echo $summary->getData('summary_id'); ?>"  onkeypress="return isNumber(event)"  />

    				<button onclick="changeSummaryamount('summarychange_<?php echo $summary->getData('summary_id'); ?>', '<?php echo $summary->getData('summary_id'); ?>', '<?php echo number_format((float) $summary->getAmount(), 2, '.', '') ?>')" title="<?php echo $this->__('Change Amount') ?>" class="scalable " type="button">
    				    <span>
    					<span>
    					    <span><?php echo $this->__('Change Amount') ?></span>
    					</span>
    				    </span>
    				</button>                                 
    				<button onclick="notChangeSummaryamount('orgsummaryparent_<?php echo $summary->getData('summary_id'); ?>', 'changesummaryparent_<?php echo $summary->getData('summary_id'); ?>')" title="<?php echo $this->__('Cancel') ?>" class="scalable " type="button">
    				    <span>
    					<span>
    					    <span><?php echo $this->__('Cancel') ?></span>
    					</span>
    				    </span>
    				</button>    
    			    </div>


    			</td>
    			<td class="a-center">
				<?php $date = ($summary->getDueDate()) ? date('M d, Y', strtotime($summary->getDueDate())) : 'N / A'; ?>
				<?php echo $date ?>
    			</td>
    			<td class="a-center">
				<?php $date = ($summary->getPaidDate()) ? date('M d, Y', strtotime($summary->getPaidDate())) : 'N / A'; ?>
				<?php echo $date ?>
    			</td>
    			<td class="a-left">
    			    <span class="<?php echo $summaryStatusMap[$summary->getStatus()]['class'] ?>">
    				<span><?php echo $summaryStatusMap[$summary->getStatus()]['label'] ?></span>
    			    </span>
    			</td>
    			<td class="a-left">
				<?php echo Mage::getStoreConfig('payment/' . $summary->getPaymentMethod() . '/title') ?>
    			</td>
    			<td class="a-center">
				<?php if ($transactionDetails !== '-'): ?>
				    <a href="javascript:void(0)" class="summary-details" id="link_<?php echo $summary->getId() ?>"><?php echo $helper->__('Details') ?></a>
				    <div id="trans_details_<?php echo $summary->getId() ?>" style="display:none;">
					<div class="entry-edit">
					    <div class="entry-edit-head">
						<h4 class="icon-head fieldset-legend"><?php echo $helper->__('Payment Details') ?></h4>
					    </div>
					    <div class="content">
						<?php echo $transactionDetails; ?>
					    </div>
					</div>
				    </div>
				<?php else: ?>
				    <?php echo $transactionDetails; ?>
				<?php endif; ?>
    			</td>
    		    </tr>

		    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <br />
    
</form>
</div>
 <script type="text/javascript">
	Event.observe(window, 'load', function () {
	    var idsJson = '<?php echo Mage::helper('core')->jsonEncode($ids) ?>'.evalJSON(true);

	    $$(".summary-details").each(function (summaryElement) {
		Event.observe($(summaryElement), 'click', function (event) {
		    var sourceElement = event.element();
		    var sourceElementId = $(sourceElement).id;
		    var splitedId = sourceElementId.split('_');

		    if ($('trans_details_' + splitedId[1]).getStyle('display') == 'none') {
			$('trans_details_' + splitedId[1]).setStyle({display: 'block', position: 'absolute', zIndex: '100', background: '#FFFFFF', textAlign: 'left'});
		    } else {
			$('trans_details_' + splitedId[1]).setStyle({display: 'none'});
		    }
		    for (var idx = 0; idx < idsJson.length; idx++) {
			if (splitedId[1] !== idsJson[idx]) {
			    if ($('trans_details_' + idsJson[idx])) {
				$('trans_details_' + idsJson[idx]).setStyle({display: 'none'});
			    }
			}

		    }
		});
	    });
	});
    </script>