<?php
/**
 * Magedelight
 * Copyright (C) 2015 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category MD
 * @package MD_Stripe
 * @copyright Copyright (c) 2015 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php 
$_code		  = MD_Stripe_Model_Cardspayment::METHOD_CODE;
 $helper	  = Mage::helper('md_stripe');
$defaultCardId	  = null;
$cardInfoData     = true;
$currentCustomer  = $this->getCustomer();
$stripeCustomerId = $currentCustomer->getMdStripeCustomerId();
$cards		  = $requestData = array();
$paymentConfig    = Mage::getSingleton('payment/config');
$ccTypes	  = $paymentConfig->getCcTypes();
$months		  = $paymentConfig->getMonths();
$years		  = $paymentConfig->getYears();
$storeId	  = (Mage::getSingleton('adminhtml/session_quote')->getStoreId() > 0) ? Mage::getSingleton('adminhtml/session_quote')->getStoreId(): Mage::app()->getStore()->getId();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>">
    <?php 
    if(Mage::getModel("md_stripe/config",array(MD_Stripe_Model_Cardspayment::METHOD_CODE,$storeId))->getIsActive()){
	$gatewayCustomerId = $currentCustomer->getMdStripeCustomerId();
	
	if($gatewayCustomerId){
	    $requestData['id'] = $gatewayCustomerId;
	    $restApiObject     = Mage::getModel('md_stripe/api_rest')
				 ->setApiType(MD_Stripe_Model_Cardspayment::METHOD_CODE)
				 ->setStore($storeId);
	    $restResponse      = $restApiObject->getCustomerCards($requestData);
	    
	    if(array_key_exists('result_data',$restResponse)){
		$restResponseObject = $restResponse['result_data'];
		$cards		    = $restResponseObject->sources->data;
		$defaultCardId	    = (string)$restResponseObject->default_source;
	    }
	}
    }
	
    if (count($cards) > 0): 
	$cardInfoData = false; 
    ?>
	<li>
	    <label for="<?php echo $_code ?>_payment_id">
		<?php echo $this->__("Select From Saved Card") ?>
	    </label>
	    
	    <div class="input-box">
		<select name="payment[md_stripe_card_id]" id="<?php echo $_code ?>_payment_id" class="required-entry">
		    <?php
		    foreach ($cards as $_card): 
			if ($helper->isInUnsavedList($stripeCustomerId, $_card->id)):
			   continue;
		       endif; 
		    ?>
			    <option value="<?php echo $_card->id ?>" <?php if ($defaultCardId == $_card->id): ?>selected="selected"<?php endif; ?>>
				<?php echo sprintf('XXXX-%s(%s, Expiry: %02d / %04d)', $_card->last4, $_card->brand, $_card->exp_month, $_card->exp_year) ?>
			    </option>
		    <?php endforeach; ?>

		    <option value="new">
			<?php echo $this->__("Use other card") ?>
		    </option>
		</select>
	    </div>
	</li>
    <?php endif; ?>
	
    <li class="<?php echo $_code ?>_new" <?php if (!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
	<label for="<?php echo $_code ?>_cc_type" class="required">
	    <em>*</em><?php echo $this->__('Credit Card Type') ?>
	</label>
	
	<div class="input-box" style="clear:left">
	    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select" disabled>
                <option value="">
		    <?php echo $this->__('--Please Select--') ?>
		</option>
		
		<?php foreach ($ccTypes as $_typeCode => $_typeName): ?>
			<option value="<?php echo $_typeCode ?>">
			    <?php echo $_typeName ?>
			</option>
		<?php endforeach ?>
            </select>
	</div>
    </li>
    
    <li class="<?php echo $_code ?>_new" <?php if (!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
	<label for="<?php echo $_code ?>_cc_number" class="required">
	    <em>*</em><?php echo $this->__('Credit Card Number') ?>
	</label>
	
	<div class="input-box">
	    <input type="text" disabled pattern="\d*" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
	</div>
    </li>
    
    <li class="<?php echo $_code ?>_new" <?php if (!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
	<label for="<?php echo $_code ?>_expiration" class="required">
	    <em>*</em><?php echo $this->__('Expiration Date') ?>
	</label>
	
	<div class="input-box">
	    <div class="v-fix">
		<select disabled id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
		    <?php 
		    //$_ccExpMonth = MD_Stripe_Block_Cards_Form::getInfoData('cc_exp_month');
		    
		    foreach ($months as $k => $v): 
		    ?>
			<option value="<?php echo $k ? $k : '' ?>">
			    <?php echo $v ?>
			</option>
		    <?php endforeach ?>
		</select>
	    </div>
	    <div class="v-fix">
		
		<select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry" disabled>
		    <?php foreach ($years as $k => $v): ?>
			<option value="<?php echo $k ? $k : '' ?>">
			    <?php echo $v ?>
			</option>
		    <?php endforeach ?>
		</select>
	    </div>
	</div>
    </li>
    <?php 
    
    echo $this->getChildHtml();
    
    if ($this->hasVerification()): 
    ?>
        <li id="<?php echo $_code ?>_cc_type_cvv_div">
	    <label for="<?php echo $_code ?>_cc_cid" class="required">
		<em>*</em><?php echo $this->__('Card Verification Number') ?>
	    </label>

	    <div class="input-box">
		<div class="v-fix">
		    <input type="text" pattern="\d*" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
		</div>
		<a href="#" class="cvv-what-is-this">
		    <?php echo $this->__('What is this?') ?>
		</a>
	    </div>
        </li>
    <?php 
    endif; 
    
    if($currentCustomer->getId()) :
	if(Mage::getModel("md_stripe/config", array(MD_Stripe_Model_Cardspayment::METHOD_CODE, Mage::app()->getStore()->getId()))->getSaveCardOptional()): ?>
		<li class="<?php echo $_code ?>_new" <?php if (!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
		    <label>&nbsp;</label>
		    <input type="checkbox" name="payment[md_stripe_save_card]" id="<?php echo $_code ?>_save_card" value="1" checked="checked" autocomplete="on" disabled/>
		    <label for="<?php echo $_code ?>_save_card" style="float:none;font-weight:normal;">
			<?php echo $this->__('Save this credit card for future use.'); ?>
		    </label>
		</li>
    <?php
	endif;
    else: 
    ?>
	<li class="<?php echo $_code ?>_new" <?php if (!$cardInfoData): ?>style="display:none;"<?php endif; ?>>
	    <input type="hidden" name="payment[md_stripe_save_card]" id="<?php echo $_code ?>_save_card" value="1" disabled/>
        </li>
    <?php endif; ?>
</ul>

