
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
						<?php 
						    $fromdate=$_product->getCountdown();
						   $producttime = strtotime($fromdate);
							$currentDate = Mage::getModel('core/date')->date('Y m d H:i:s');
							 $time=date("Y m d H:i:s",$producttime);
							$prodid = $_product->getId();
						    
							$helper = Mage::helper("countdown");
						
						 ?>

	<?php if($time > $currentDate  || !$_product->getCountdown()): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
			
			
					
                  <?php if($_product->isSaleable()): ?>
					<?php if(!($_product->getCountdown())):?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php endif; ?>
                   
					
					
				<!-- //  Start of Timer -->
				<?php if($_product->getCountdown()):?>
					<?php if($time > $currentDate):?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    
                    
						
						 <div class="countdown">
						 
	<script type="text/javascript">
		function dateFromString(str) {
			var a = jQuery.map(str.split(/[^0-9]/), function (s) { 
				return parseInt(s, 10) 
			});
			return new Date(a[0], a[1] - 1 || 0, a[2] || 1, a[3] || 0, a[4] || 0, a[5] || 0, a[6] || 0);
		}
		jQuery(window).load(function(){
			
		var startDate = new Date() / 1000;
		var endDate = dateFromString('<?php echo $time?>') / 1000;
		var dateNow = new Date() / 1000;
		
		
			JBCountDown({

				secondsColor: "<?php echo ($helper->getSecondColor() == null)? "#E92026" : $helper->getSecondColor();?>",
				secondsGlow: "none",
	
				minutesColor: "<?php echo ($helper->getMinuteColor() == null)? "#E92026" : $helper->getMinuteColor();?>",
				minutesGlow: "none",
	
				hoursColor: "<?php echo ($helper->getHourColor() == null)? "#E92026" : $helper->getHourColor();?>",
				hoursGlow: "none",
	
				daysColor: "<?php echo ($helper->getDayColor() == null)? "#E92026" : $helper->getDayColor();?>",
				daysGlow: "none",
					
				startDate: startDate,
				endDate: endDate,
				now: dateNow,
				id:"<?=$prodid?>"

			});
			
		});
		
	</script>
	
	<div class="deliverymessage"><?php echo $_product->getDeliveryMessage()?></div>
	<div class="clock">
		<!-- Days-->
		<div class="clock_days" id="clock_days<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_days<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_days">
						<?php echo $this->__("D")?></p>
				</div>
			</div>
		</div>
		<!-- Days -->
		<!-- Hours -->
		<div class="clock_hours" id="clock_hours<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_hours<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_hours">
						<?php echo $this->__("H")?></p>
				</div>
			</div>
		</div>
		<!-- Hours -->
		<!-- Minutes -->
		<div class="clock_minutes" id="clock_minutes<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_minutes<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_minutes">
						<?php echo $this->__("M")?></p>
				</div>
			</div>
		</div>
		<!-- Minutes -->
		<!-- Seconds -->
		<div class="clock_seconds" id="clock_seconds<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_seconds<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_seconds">
						<?php echo $this->__("S")?></p>
				</div>
			</div>
		</div>
		<!-- Seconds -->
	</div>
</div>
<?php else: ?>
  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>	
<?php endif; ?>	
<?php endif; ?>
				
		<!-- //  End of Timer -->
					
					
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
		<?php endif; ?>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
	
					<?php 
						   $fromdate=$_product->getCountdown();
						   $producttime = strtotime($fromdate);
							$currentDate = Mage::getModel('core/date')->date('Y m d H:i:s');
							 $time=date("Y m d H:i:s",$producttime);
							$prodid = $_product->getId();
						    
							$helper = Mage::helper("countdown");
							
						 ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
		<?php if($time > $currentDate  || !$_product->getCountdown()): ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
			

				
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
				
				
				
				
						 
						 
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
					<?php if(!($_product->getCountdown())):?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php endif; ?>
                   
					
					
				<!-- //  Start of Timer -->
				<?php if($_product->getCountdown()):?>
					<?php if($time > $currentDate):?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    
                    
					
						 <div class="countdown">
						
	<script type="text/javascript">
		function dateFromString(str) {
			var a = jQuery.map(str.split(/[^0-9]/), function (s) { 
				return parseInt(s, 10) 
			});
			return new Date(a[0], a[1] - 1 || 0, a[2] || 1, a[3] || 0, a[4] || 0, a[5] || 0, a[6] || 0);
		}
		jQuery(window).load(function(){
			
		var startDate = new Date() / 1000;
		var endDate = dateFromString('<?php echo $time?>') / 1000;
		var dateNow = new Date() / 1000;
	
		
			JBCountDown({

				secondsColor: "<?php echo ($helper->getSecondColor() == null)? "#E92026" : $helper->getSecondColor();?>",
				secondsGlow: "none",
	
				minutesColor: "<?php echo ($helper->getMinuteColor() == null)? "#E92026" : $helper->getMinuteColor();?>",
				minutesGlow: "none",
	
				hoursColor: "<?php echo ($helper->getHourColor() == null)? "#E92026" : $helper->getHourColor();?>",
				hoursGlow: "none",
	
				daysColor: "<?php echo ($helper->getDayColor() == null)? "#E92026" : $helper->getDayColor();?>",
				daysGlow: "none",
					
				startDate: startDate,
				endDate: endDate,
				now: dateNow,
				id:"<?=$prodid?>"

			});
			
		});
		
	</script>
	
	<div class="deliverymessage"><?php echo $_product->getDeliveryMessage()?></div>
	<div class="clock">
		<!-- Days-->
		<div class="clock_days" id="clock_days<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_days<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_days">
						<?php echo $this->__("D")?></p>
				</div>
			</div>
		</div>
		<!-- Days -->
		<!-- Hours -->
		<div class="clock_hours" id="clock_hours<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_hours<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_hours">
						<?php echo $this->__("H")?></p>
				</div>
			</div>
		</div>
		<!-- Hours -->
		<!-- Minutes -->
		<div class="clock_minutes" id="clock_minutes<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_minutes<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_minutes">
						<?php echo $this->__("M")?></p>
				</div>
			</div>
		</div>
		<!-- Minutes -->
		<!-- Seconds -->
		<div class="clock_seconds" id="clock_seconds<?=$prodid?>">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_seconds<?=$prodid?>" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_seconds">
						<?php echo $this->__("S")?></p>
				</div>
			</div>
		</div>
		<!-- Seconds -->
	</div>
</div>
<?php else: ?>
  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>	
<?php endif; ?>	
<?php endif; ?>
				
		<!-- //  End of Timer -->
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
			 <?php endif ?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
