<?php
/**
 * Magedelight
 * Copyright (C) 2014 Magedelight <info@magedelight.com>
 *
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category MD
 * @package MD_Partialpayment
 * @copyright Copyright (c) 2014 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
$helper		       = Mage::helper('md_partialpayment');
$partialPaymentOptions = $this->getPartialPaymentOption();
$slabs		       = Mage::getModel('md_partialpayment/slabs');
$status		       = $initialPaymentAmount = $additionalPaymentAmount = $frequencyPayment = $installments = null;
$useConfigInstallments = $customerGroups = null;
$ruleId		       = Mage::app()->getRequest()->getParam('id');
$model		       = Mage::getModel('md_partialpayment/rule')->load($ruleId);
$priority	       = $model->getData('priority');
$installments	       = $model->getData('installment_settings');

if(!$partialPaymentOptions || !$partialPaymentOptions->getId() || !is_object($partialPaymentOptions)) {
    $isNew = true;
} else {
    $isNew = false;
}

if (!$isNew) {
    if($partialPaymentOptions->getId()){
	if(!is_null($partialPaymentOptions->getData('status'))){
	    $status = $partialPaymentOptions->getData('status');
	} 
	
	if(!is_null($partialPaymentOptions->getData('initial_payment_amount'))) {
	    $initialPaymentAmount = $partialPaymentOptions->getData('initial_payment_amount');
	} 
	
	if(!is_null($partialPaymentOptions->getData('additional_payment_amount'))){
	    $additionalPaymentAmount = $partialPaymentOptions->getData('additional_payment_amount');
	} 
	
	if(!is_null($partialPaymentOptions->getData('customer_groups'))) {
	    $customerGroups = $partialPaymentOptions->getData('customer_groups');
	} 
	
	if(!is_null($partialPaymentOptions->getData('frequency_payment'))) {
	    $frequencyPayment = $partialPaymentOptions->getData('frequency_payment');
	} 
	
	if(!is_null($partialPaymentOptions->getData('installments'))) {
	    $installments = $partialPaymentOptions->getData('installments');
	} 
	
	if(!is_null($partialPaymentOptions->getData('use_config_installments'))){
	    $useConfigInstallments = $partialPaymentOptions->getData('use_config_installments'); 
	} 
    }
}


if (!empty($installments)) {
    $installments = unserialize($installments);
}
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $helper->__('Item Information') ?></h4>
    </div>
    <div class="fieldset " id="partialplan_form">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
		    <tr>
			<td class="label" for="title"><label><?php echo $this->__('Title') ?></label></td>
			<td class="value">
			    <input class="input-text required-entry" type="text" id="title" name="title" value="<?php echo $model->getData('title') ?>">
			</td>
		    </tr>
		    <tr>
			<td class="label" for="rule_status"><label><?php echo $this->__('Status') ?></label></td>
			<td class="value">
			    <?php
			    $ruleStatus = $model->getData('rule_status');
			    $class1	= $class2 = '';
			    
			    if (empty($ruleStatus) || $ruleStatus == 1) {
				$class1 = 'selected';
			    } else if ($ruleStatus == 2) {
				$class2 = 'selected';
			    }
			    ?>
			    <select id="rule_status" name="rule_status" class="required-entry select">
				<option value="1" <?php echo $class1 ?>><?php echo $this->__('Enabled') ?></option>
				<option value="2" <?php echo $class2 ?>><?php echo $this->__('Disabled') ?></option>
			    </select>
			</td>
		    </tr>
		    <tr>
			<td class="label" for="priority">
			    <label><?php echo $this->__('Priority') ?></label>
			</td>
			<td class="value">
			    <input class="input-text required-entry validate-greater-than-zero" type="text" id="priority" name="priority" value="<?php echo empty($priority) ? 1 : $priority ?>">
			</td>
		    </tr>
		    <tr>
			<td class="label" for="initial_payment_amount_type"><label><?php echo $this->__('Initial Payment Amount Type') ?></label></td>
			<td class="value">
			    <select id="initial_payment_amount_type" name="initial_payment_amount_type" class="required-entry select">
				<?php
				$selectedOpt = $model->getData('initial_payment_amount_type');
				$options     = Mage::getModel('md_partialpayment/system_config_source_payment_type')->toOptionArray();
				
				foreach ($options as $optKey => $optValue) {
				    if ($selectedOpt == $optKey) {
				?>
					<option id="<?php echo $optKey ?>" name="<?php echo $optKey ?>" selected> 
				<?php } else { ?>
					<option id="<?php echo $optKey ?>" name="<?php echo $optKey ?>"> 
				<?php } ?>
					    <?php echo $optValue ?>
					</option>
				<?php } ?>
			    </select>
			</td>
		    </tr>
		    <tr>
			<td class="label" for="initial_payment_amount"><label><?php echo $this->__('Initial Payment Amount') ?></label></td>
			<td class="value">
			    <input class="required-entry input-text validate-number" type="initial_payment_amount" id="initial_payment_amount" name="initial_payment_amount" value="<?php echo $model->getData('initial_payment_amount') ?>">
			</td>
		    </tr>
                    <tr>
                        <td class="label"><label for="partialpayment_frequency_payment"><?php echo $helper->__('Installment Settings') ?></label></td>
                        <td colspan="10" class="grid tier">
			    <?php $_checked = ($useConfigInstallments == 1 || $isNew) ? 'checked="checked"' : '' ?>
                            <table cellspacing="0" class="data border" id="installment_slabs_table">
                                <col width="135" />
                                <col width="120" />
                                <col />
                                <col width="1" />
                                <thead>
                                    <tr class="headings">
                                        <th><?php echo $helper->__('No of Installments') ?></th>
                                        <th><?php echo $helper->__('Additional Fee Type') ?></th>
                                        <th><?php echo $helper->__('Additional Fee') ?></th>
                                        <th>&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody id="partialpayment_slabs_container"></tbody>
                                <tfoot>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td colspan="4" class="a-right"><?php echo $this->getInstallmentSlabAddButtonHtml() ?></td>
                                    </tr>
                                </tfoot>
                            </table>
                            <p class="note"><span><?php echo $helper->__('Minimum installments should be greater than one.') ?></span></p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script type="text/javascript">
    var installmentSlabsTemplate = '<tr>'
	    + '<td><input class="input-text required-entry validate-greater-than-zero" type="text" name="partialpayment[slabs][{{index}}][unit]" id="partialpayment_slabs_{{index}}_unit" value="{{unit}}" /></td>'
	    + '<td>'
	    + '<select name="partialpayment[slabs][{{index}}][price_type]" class="select validate-select" id="partialpayment_slabs_{{index}}_price_type">'
	    + '<option value="<?php echo $slabs::INSTALLMENT_SLAB_PRICE_FIXED ?>"><?php echo $helper->__('Fixed') ?></option>'
	    + '<option value="<?php echo $slabs::INSTALLMENT_SLAB_PRICE_PERCENTAGE ?>"><?php echo $helper->__('Percentage') ?></option>'
	    + '</select>'
	    + '</td>'
	    + '<td><input class="input-text required-entry" type="text" name="partialpayment[slabs][{{index}}][price]" id="partialpayment_slabs_{{index}}_price" value="{{price}}" /></td>'
	    + '<td><input type="hidden" name="partialpayment[slabs][{{index}}][delete]" class="delete" value="" id="partialpayment_slabs_{{index}}_delete" /><?php echo $this->getInstallmentSlabDeleteButtonHtml() ?></td>'
	    + '</tr>';
    var slabOption = {
	template  : new Template(installmentSlabsTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', '')),
	itemsCount: 0,
	addItem	  : function (data) {
	    if (!data) {
		data = {};
	    }
	    data.index = 'slab_option_' + this.itemsCount;
	    
	    Element.insert($('partialpayment_slabs_container'), {
		bottom: this.template.evaluate(data)
	    });
	    
	    var priceElement = 'partialpayment_slabs_' + data.index + '_price';
	    
	    Event.observe('partialpayment_slabs_' + data.index + '_price_type', 'change', function (event) {
		var typeElement = Event.findElement(event, 'select');
		if (typeElement.value == <?php echo $slabs::INSTALLMENT_SLAB_PRICE_PERCENTAGE ?>) {
		    $(priceElement).addClassName('validate-percents');
		    
		    if ($(priceElement).hasClassName('validate-not-negative-number')) {
			$(priceElement).removeClassName('validate-not-negative-number');
		    }
		} else {
		    $(priceElement).addClassName('validate-not-negative-number');
		    
		    if ($(priceElement).hasClassName('validate-percents')) {
			$(priceElement).removeClassName('validate-percents');
		    }
		}
	    });
	    
	    $('partialpayment_slabs_' + data.index + '_price_type').select("option").each(function (node) {
		if (data.price_type == $(node).value) {
		    $(node).selected = true;
		    
		    if ($(node).value == <?php echo $slabs::INSTALLMENT_SLAB_PRICE_PERCENTAGE ?>) {
			$(priceElement).addClassName('validate-percents');
			
			if ($(priceElement).hasClassName('validate-not-negative-number')) {
			    $(priceElement).removeClassName('validate-not-negative-number');
			}
		    } else {
			$(priceElement).addClassName('validate-not-negative-number');
			
			if ($(priceElement).hasClassName('validate-percents')) {
			    $(priceElement).removeClassName('validate-percents');
			}
		    }
		}
	    });
	    this.itemsCount++;

	},
	deleteItem: function (event) {
	    var tr = Event.findElement(event, 'tr');
	    if (tr) {
		Element.select(tr, '.delete').each(function (element) {
		    element.value = '1';
		});

		Element.select(tr, ['input', 'select']).each(function (element) {
		    element.setAttribute("name", "");
		    element.hide();
		});

		Element.hide(tr);
		Element.addClassName(tr, 'no-display template');
	    }
	    return false;
	}
    };
<?php 
if(!empty($installments)) {
    foreach ($installments as $installmentId => $slab) { ?>
        slabOption.addItem(<?php echo json_encode($slab) ?>);
<?php 
    } 
}
?>
</script>