<div class="kodematix-socialconnect-register">   
    <div class="<?php echo $this->_getColSet(); ?>">
        <?php if($this->_googleEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> kodematix-socialconnect-register-google">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Google Connect') ?></h2>
                <p><?php echo $this->__('Register With Your Google Account.') ?></p>
                <p><?php echo $this->getChildHtml('kodematix_socialconnect_checkout_google_login')?></p>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_facebookEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> kodematix-socialconnect-register-facebook">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Facebook Connect') ?></h2>
                <p><?php echo $this->__('Register With Your Facebook Account.') ?></p>
                <p><?php echo $this->getChildHtml('kodematix_socialconnect_checkout_facebook_login')?></p>
            </div>
        </div>
        <?php endif; ?>
        <?php if($this->_twitterEnabled()): ?>
        <div class="<?php echo $this->_getCol(); ?> kodematix-socialconnect-register-twitter">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Twitter Connect') ?></h2>
                <p><?php echo $this->__('Register With Your Twitter Account.') ?></p>
                <p><?php echo $this->getChildHtml('kodematix_socialconnect_checkout_twitter_login')?></p>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>