<?php
/**
* Magedelight
* Copyright (C) 2014 Magedelight <info@magedelight.com>
*
* NOTICE OF LICENSE
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
*
* @category MD
* @package MD_Partialpayment
* @copyright Copyright (c) 2014 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
	$_code      = 'sagepayserver';
	$tokenCards = $this->getTokenCards($_code);
	$cTokens    = ($tokenCards->getSize()>0 && $this->canUseToken());
	$sageStyle  = '';
?>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">

	<?php echo $this->getChildHtml('token.cards.li'); ?>

	<ul class="form-list paymentsage<?php echo $_code ?>">
	    <li id="serversecure"<?php echo $sageStyle; ?>>
	        <span>
	            <?php
	            	$_secImage = '<img class="sagepay-server-content-image" src="' . $this->getSkinUrl('sagepaysuite/images/secured-by-sage-pay.png') . '" />';
	            	echo preg_replace('/{{secured_logo}}/', $_secImage, Mage::getStoreConfig('payment/sagepayserver/selected_description'));
	            ?>
	        </span>
	    </li>

	<?php if($this->canUseToken()): ?>
		<li<?php echo $sageStyle; ?>>
			<label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__('Do you wish to have your credit card details remembered for faster checkout next time?'); ?></label>&nbsp;
			<input checked="checked" type="checkbox" name="<?php echo $_code ?>[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
		</li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_nickname_li" >
            <label for="<?php echo $_code ?>_cc_nickname"><?php echo $this->__('Credit Card Description') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Credit Card Description') ?>" class="input-text" id="<?php echo $_code ?>_cc_nickname" name="<?php echo $_code ?>[cc_nickname]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_nickname')) ?>" />
            </div>
        </li>
	<?php endif; ?>

	</ul>
</div>