<?php
/**
* Magedelight
* Copyright (C) 2014 Magedelight <info@magedelight.com>
*
* NOTICE OF LICENSE
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
*
* @category MD
* @package MD_Partialpayment
* @copyright Copyright (c) 2014 Mage Delight (http://www.magedelight.com/)
* @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
* @author Magedelight <info@magedelight.com>
*/
    $_code       = 'sagepaydirectpro';
    $tokenCards  = $this->getTokenCards($_code);
    $cTokens     = ($tokenCards->getSize()>0 && $this->canUseToken());
    $sageStyle   = '';
    $_directMode = Mage::getStoreConfig('payment/sagepaydirectpro/mode');
?>
<dd>
<div id="payment_form_<?php echo $_code ?>" style="display:none;">

<?php echo $this->getChildHtml(); ?>
<ul class="form-list paymentsage<?php echo $_code ?>">

    <?php if($this->canUseToken()): ?>
        <li<?php /*echo $sageStyle;*/ if($tokenCards->getSize()==0 || $cTokens): echo ' style="display:none;"'; endif; ?>>
        	<a class="usexist<?php echo $_code; ?>" href="javascript:void(0)" onclick="toggleSagepayDiv(0,'<?php echo $_code ?>');"><?php echo $this->__('Saved Credit Cards'); ?></a>
        </li>
    <?php endif; ?>

    <li<?php echo $sageStyle; ?>>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="<?php echo $_code ?>[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li<?php echo $sageStyle; ?>>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="<?php echo $_code ?>[cc_type]" onchange="changecsvclass(this);" class="required-entry validate-ccsgpdp-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li<?php echo $sageStyle; ?>>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input autocomplete="off" type="text" id="<?php echo $_code ?>_cc_number" name="<?php echo $_code ?>[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text required-entry validate-ccsgpdp-number validate-ccsgpdp-type" value="" />
        </div>
    </li>
    <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="<?php echo $_code ?>[cc_exp_month]" class="month validate-cc-exp required-entry">
                <?php $_ccExpMonth = Mage::getSingleton('payment/config')->getMonths(); ?>
                <?php foreach ($_ccExpMonth as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = Mage::getSingleton('payment/config')->getYears() ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="<?php echo $_code ?>[cc_exp_year]" class="year required-entry">
                <?php foreach ($_ccExpYear as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input style="width:3em !important;" autocomplete="off" type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-ccsgpdp-cvn" id="<?php echo $_code ?>_cc_cid" name="<?php echo $_code ?>[cc_cid]" value="" />
            </div>
        </div>
    </li>

	<?php if ($this->allowGiftAid()): ?>
    <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_giftaid_div">
        <label for="<?php echo $_code ?>_cc_giftaid"><?php echo $this->__('Donate Taxes') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="checkbox" title="<?php echo $this->__('Donate Taxes') ?>" class="input-text checkbox" id="<?php echo $_code ?>_cc_giftaid" name="<?php echo $_code ?>[cc_giftaid]" />
            </div>
        </div>
    </li>
    <?php endif; ?>

	<?php if($this->canUseToken()): ?>
		<li<?php echo $sageStyle; ?>>
			<label for="remembertoken-<?php echo $_code; ?>"><?php echo $this->__('Do you wish to have your credit card details remembered for faster checkout next time?'); ?></label>&nbsp;
			<input checked="checked" type="checkbox" name="<?php echo $_code ?>[remembertoken]" value="1" id="remembertoken-<?php echo $_code; ?>" />
		</li>
        <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_nickname_li" >
            <label for="<?php echo $_code ?>_cc_nickname"><?php echo $this->__('Credit Card Description') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Credit Card Description') ?>" class="input-text" id="<?php echo $_code ?>_cc_nickname" name="<?php echo $_code ?>[cc_nickname]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_nickname')) ?>" />
            </div>
        </li>
	<?php endif; ?>

    <?php if ($this->hasSsCardType()): ?>
    <li<?php echo $sageStyle; ?> id="<?php echo $_code ?>_cc_type_ss_div">
    <ul<?php echo $sageStyle; ?> class="inner-form">
        <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo Only') ?></label></li>
        <li>
            <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
            <span class="input-box">
                <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
            </span>
        </li>

        <li>
            <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
            <div class="input-box">
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
        </li>

        <li class="adv-container">&nbsp;</li>
   </ul>
    <script type="text/javascript">

    var saveTokenChecked<?php echo $_code ?> = function(){
        if($('remembertoken-<?php echo $_code; ?>').checked){
            $('<?php echo $_code ?>_cc_nickname_li').show();
        }else{
            $('<?php echo $_code ?>_cc_nickname_li').hide();
        }
    };

	var SSChecked<?php echo $_code ?> = function() {
            var elm = $('<?php echo $_code ?>_cc_type');

			if(elm.value=='' || ($$('ul#payment_form_sagepaydirectpro li.tokencard-radio input[type="radio"]:enabled').length > 0)){
				$('<?php echo $_code ?>_cc_type_ss_div').hide();
        		return;
        	}
            if (['SOLO','SWITCH'].indexOf(elm.value) != -1) {
                $('<?php echo $_code ?>_cc_type_ss_div').show();
            } else {
                $('<?php echo $_code ?>_cc_type_ss_div').hide();
            }
    };

    Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
    Event.observe($('<?php echo $_code ?>_cc_number'), 'blur', SSChecked<?php echo $_code ?>);

    if(typeof $('remembertoken-<?php echo $_code; ?>') != 'undefined' && $('remembertoken-sagepayserver') != null){
        Event.observe($('remembertoken-<?php echo $_code; ?>'), 'change', saveTokenChecked<?php echo $_code ?>);
    }

    SSChecked<?php echo $_code ?>();

    Validation.addAllThese([
        ['validate-cc-ukss', 'Please enter issue number or start date for switch/solo card type.', function(v,elm) {
                  var endposition;

                  if (elm.id.match(/(.)+_cc_issue$/)) {
                      endposition = elm.id.indexOf('_cc_issue');
                  } else if (elm.id.match(/(.)+_start_month$/)) {
                      endposition = elm.id.indexOf('_start_month');
                  } else {
                      endposition = elm.id.indexOf('_start_year');
                  }

                  var prefix = elm.id.substr(0,endposition);

                  var ccTypeContainer = $(prefix + '_cc_type');

                  if (!ccTypeContainer) {
                        return true;
                  }
                  var ccType = ccTypeContainer.value;

                  if(ccType!='SS'){
                      return true;
                  }

                  $(prefix + '_cc_issue').advaiceContainer
                    = $(prefix + '_start_month').advaiceContainer
                    = $(prefix + '_start_year').advaiceContainer
                    = $(prefix + '_cc_type_ss_div').down('ul li.adv-container');

                  var ccIssue   =  $(prefix + '_cc_issue').value;
                  var ccSMonth  =  $(prefix + '_start_month').value;
                  var ccSYear   =  $(prefix + '_start_year').value;

                  if((!ccIssue && !ccSMonth && !ccSYear) ||
                     (!ccIssue && !ccSMonth && ccSYear)  ||
                     (!ccIssue && ccSMonth && !ccSYear)
                  ){
                      return false;
                  }

                  return true;

        }]
    ]);
    </script>
</li>
<?php endif; ?>
</ul>
</div>
</dd>