<?php $time = $this->getTime();
if($time != null):
$helper = Mage::helper("countdown");
?>
<div class="countdown">
	<script type="text/javascript">
		function dateFromString(str) {
			var a = jQuery.map(str.split(/[^0-9]/), function (s) { 
				return parseInt(s, 10) 
			});
			return new Date(a[0], a[1] - 1 || 0, a[2] || 1, a[3] || 0, a[4] || 0, a[5] || 0, a[6] || 0);
		}
		var startDate = new Date() / 1000;
		var endDate = dateFromString('<?php echo $time?>') / 1000;
		var dateNow = new Date() / 1000;
		jQuery(window).load(function(){
			JBCountDown({
				secondsColor: "<?php echo ($helper->getSecondColor() == null)? "#E92026" : $helper->getSecondColor();?>",
				secondsGlow: "none",
	
				minutesColor: "<?php echo ($helper->getMinuteColor() == null)? "#E92026" : $helper->getMinuteColor();?>",
				minutesGlow: "none",
	
				hoursColor: "<?php echo ($helper->getHourColor() == null)? "#E92026" : $helper->getHourColor();?>",
				hoursGlow: "none",
	
				daysColor: "<?php echo ($helper->getDayColor() == null)? "#E92026" : $helper->getDayColor();?>",
				daysGlow: "none",
	
				startDate: startDate,
				endDate: endDate,
				now: dateNow
			});
		});
	</script>
	<div class="deliverymessage"><?php echo $this->getDeliveryMessage()?></div>
	<div class="clock">
	
		<div class="clock_days">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_days" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_days">
						<?php echo $this->__("Days")?></p>
				</div>
			</div>
		</div>
		
		<div class="clock_hours">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_hours" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_hours">
						<?php echo $this->__("Hours")?></p>
				</div>
			</div>
		</div>
		
		<div class="clock_minutes">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_minutes" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_minutes">
						<?php echo $this->__("Mins")?></p>
				</div>
			</div>
		</div>
	
		<div class="clock_seconds">
			<div class="bgLayer">
				<div class="topLayer">
				</div>
				<canvas id="canvas_seconds" width="70" height="70">
					</canvas>
				<div class="text">
					<p class="val">
						0</p>
					<p class="type_seconds">
						<?php echo $this->__("Secs")?></p>
				</div>
			</div>
		</div>
		
	</div>
</div>
<?php endif;?>